Implement MultiSelectComboBoxPicker jmix-framework/jmix_1337
jmix-framework/jmix pull request #1504
Opened 2023-03-15 10:55 UTC by KremnevDmitry

2023-03-15 14:46 UTC, glebfox requested changes

2023-03-15 14:46 UTC, glebfox commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/EntityPickerComponent.java
> +    default boolean isMultiValuePicker() {
This API isn't related to pickers.

2023-03-15 14:46 UTC, glebfox commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/EntityCollectionFieldDelegate.java
> +    public void checkValueType(@Nullable T value) {
Unused

2023-03-16 13:16 UTC, KremnevDmitry commented
Branch will be changed due to breaking changes

2023-03-16 13:16 UTC, closed without merging