[GenericFilter] Support custom conditions and configurations
jmix-framework/jmix pull request #1585
Opened 2023-04-11 14:57 UTC by KremnevDmitry

[GenericFilter] Support custom conditions jmix-framework/jmix#1444
[GenericFilter] Support configurations jmix-framework/jmix#1445

2023-04-24 14:36 UTC, glebfox requested changes

2023-04-26 13:47 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/logicalfilter/LogicalFilterComponent.java
> +    enum Operation implements EnumClass<String> {
I suggest not making any changes.

2023-04-26 13:47 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/propertyfilter/PropertyFilter.java
> +    public enum Operation implements EnumClass<String> {
I suggest not making any changes.

2023-04-27 10:06 UTC, KremnevDmitry commented
Drafted

New PR: https://github.com/jmix-framework/jmix/pull/1653

2023-05-30 07:04 UTC, KremnevDmitry commented
Closed

New PR: https://github.com/jmix-framework/jmix/pull/1653

2023-05-30 07:04 UTC, closed without merging