[GenericFilter] Support custom conditions and configurations
jmix-framework/jmix pull request #1653
Opened 2023-04-27 10:01 UTC by KremnevDmitry

2023-05-29 13:36 UTC, glebfox requested changes

2023-05-29 13:36 UTC, glebfox commented on jmix-flowui/flowui-data/src/main/java/io/jmix/flowuidata/genericfilter/FlowuiDataGenericFilterSupport.java
> +public class FlowuiDataGenericFilterSupport extends GenericFilterSupport {
Something odd with Configuration editor. Checkboxes do not handles their label themself, as a result they are misaligned.

<img width="841" alt="Screenshot 2023-05-29 at 17 23 01" src="https://github.com/jmix-framework/jmix/assets/6077149/0562deb3-0c68-4ffd-9f13-6dfd92167ed7">

See a default defauilt view as a reference:

<img width="1200" alt="Screenshot 2023-05-29 at 17 23 09" src="https://github.com/jmix-framework/jmix/assets/6077149/6c2603d5-41af-4be5-8ddd-195f3cf05cd5">

2023-05-29 13:36 UTC, glebfox commented on jmix-flowui/flowui-data/src/main/java/io/jmix/flowuidata/entity/FilterConfiguration.java
> +public class FilterConfiguration implements Serializable {
Support in FilterUrlQueryParameters

2023-05-29 13:37 UTC, glebfox commented
Some visual bug appears that makes filter filicker:

https://github.com/jmix-framework/jmix/assets/6077149/1c77e14e-ac9d-48f3-8aa0-25767c41dfcf

2023-05-30 10:50 UTC, KremnevDmitry commented on jmix-flowui/flowui-data/src/main/java/io/jmix/flowuidata/entity/FilterConfiguration.java
> +public class FilterConfiguration implements Serializable {
To be discussed

2023-05-31 11:16 UTC, glebfox approved these changes

2023-05-31 11:20 UTC, merged