Update russian translation of Quartz add-on
jmix-framework/jmix pull request #1839
Opened 2023-06-14 12:52 UTC by daring2

Original PR - #1329

Changes:
- add translation for add-on entities, properties, enums.
- change JobModel entity caption from "Задача" to "Задание".
- fix some typos (for example, `jobDataParamKeyIsRequired`, `jobDataParamKeyAlreadyExistsValidationMessage` messages).

2023-06-15 07:04 UTC, Gavrilov-Ivan commented on jmix-translations/content/io/jmix/quartz/messages_ru.properties
> +io.jmix.quartz.model/JobState.PAUSED=Приостановлено
There should be the same form for both states:
'Активно' - 'Приостановлено' or 'Активное' - 'Приостановленное'.
The first one is a little better, I think.

2023-06-15 07:05 UTC, Gavrilov-Ivan commented on jmix-translations/content/io/jmix/quartzui/messages_ru.properties
> +                    <li>0 0 8-10 * * * - запускать каждый день в 8:00, 9:00 and 10:00</li>\
and -> и

2023-06-15 07:05 UTC, Gavrilov-Ivan commented on jmix-translations/content/io/jmix/quartzui/messages_ru.properties
> +                    <li>0 0/30 8-10 * * * - запускать каждый день в 8:00, 8:30, 9:00, 9:30 and 10:00</li>\
and -> и

2023-06-15 07:12 UTC, Gavrilov-Ivan commented on jmix-translations/content/io/jmix/quartzui/messages_ru.properties
> +                    <li>Ограниченное количество запусков - задание запустится 'Количество повторений' + 1 (первый запуск)\
Missed 'раз'

2023-06-15 07:19 UTC, Gavrilov-Ivan requested changes
Hello.
Added some comments.
And please add the same changes (from quartzui) to quartzflowui package.

2023-06-15 09:59 UTC, daring2 commented on jmix-translations/content/io/jmix/quartz/messages_ru.properties
> +io.jmix.quartz.model/JobState.PAUSED=Приостановлено
Fixed

2023-06-15 10:01 UTC, daring2 commented
I fixed typos and updated quartzflowui messages.

2023-06-16 07:43 UTC, Gavrilov-Ivan approved these changes

2023-06-16 07:44 UTC, merged