JMX console screen in flowui (1803)
jmix-framework/jmix pull request #2052
Opened 2023-07-19 08:04 UTC by breakingfox

2023-08-27 16:28 UTC, glebfox requested changes

2023-08-27 16:28 UTC, glebfox commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/app/jmxconsole/MBeanAttributeDetailView.java
> +                .withFixedSize(true)
Why fixed size? This dialog isn't so big, you can use width=100% for a field. Probably, with maxWidth=25em just in case.

2023-08-27 16:28 UTC, glebfox commented on jmix-flowui/flowui/src/main/resources/io/jmix/flowui/app/jmxconsole/mbean-attribute-detail-view.xml
> +        <div id="valueContainerDiv"/>
do we need a container? can't we add a component by index to the first place in a view?

P.S. `valueContainerDiv` is a bad id name. it'a a `fieldWrapper` or `valueComponentWrapper`

2023-08-27 16:28 UTC, glebfox commented on jmix-flowui/flowui/src/main/resources/io/jmix/flowui/app/jmxconsole/mbean-operation-result-view.xml
> +    <layout width="60em">
![image](https://github.com/jmix-framework/jmix/assets/6077149/3bb8fcfb-05a7-4143-a8aa-c6334ef552ef)


P.S. Set size for a dialog itself and make it resizable.

2023-08-27 16:28 UTC, glebfox commented on jmix-flowui/flowui/src/main/resources/io/jmix/flowui/app/jmxconsole/mbean-operation-result-view.xml
> +        <vbox id="resultVBox" expand="resultContainer">
1. disable padding
2. Currently dialog has auto height, so neither expand not scroller make sense

2023-08-27 16:28 UTC, glebfox commented on jmix-flowui/flowui/src/main/resources/io/jmix/flowui/app/jmxconsole/mbean-operation-result-view.xml
> +        <action id="closeAction" type="view_close" icon="CHECK" text="msg://close"/>
No need in custom message, use actions.Close

2023-08-27 16:28 UTC, glebfox commented on jmix-flowui/flowui/src/main/resources/io/jmix/flowui/app/jmxconsole/mbean-operation-result-view.xml
> +            <button id="exportBtn" icon="DOWNLOAD" text="msg://actions.Export" enabled="false"/>
Create `export` action and assign to a button.

2023-08-27 16:28 UTC, glebfox commented on jmix-flowui/flowui/src/main/resources/io/jmix/flowui/app/jmxconsole/mbean-operation-result-view.xml
> +        <hbox classNames="buttons-panel">
we don't need this className here. Instead, define `id`.

2023-08-27 16:28 UTC, glebfox commented on jmix-flowui/flowui/src/main/resources/io/jmix/flowui/app/jmxconsole/mbean-detail-view.xml
> +        <action id="close" type="detail_discard" text="msg://close"/>
No need in custom message, use `actions.Close` instead.

2023-08-27 16:28 UTC, glebfox commented on jmix-flowui/flowui/src/main/resources/io/jmix/flowui/app/jmxconsole/mbean-detail-view.xml
> +            <button id="closeBtn" action="close" themeNames="primary"/>
`close` rarely marked as primary. Especially the one that works as discard

2023-08-27 16:28 UTC, glebfox commented on jmix-flowui/flowui/src/main/resources/io/jmix/flowui/app/jmxconsole/mbean-detail-view.xml
> +                    <action id="refresh" text="msg:///actions.Refresh" type="list_refresh"/>
`list_refresh` already has text=actions.Refresh

2023-08-27 16:28 UTC, glebfox commented on jmix-flowui/flowui/src/main/resources/io/jmix/flowui/app/jmxconsole/mbean-detail-view.xml
> +        <split orientation="VERTICAL" width="100%">
Let's consider removing this component. Currently, it's very inconvenient to use the view with split.

2023-08-27 16:28 UTC, glebfox commented on jmix-flowui/flowui/src/main/resources/io/jmix/flowui/app/jmxconsole/mbean-detail-view.xml
> +                <textField id="operationsSearchField" placeholder="msg://operationsSearchField.placeholder"/>
let's make this field bigger, something like this: width=100%, maxWidth=25em

2023-08-27 16:28 UTC, glebfox commented on jmix-flowui/flowui/src/main/resources/io/jmix/flowui/app/jmxconsole/mbean-detail-view.xml
> +                    <action id="edit" text="msg://attribute.edit" icon="PENCIL" type="list_itemTracking"/>
icon=PENCIL is used by default. `text` also the same, so no need in custom message

2023-08-27 16:28 UTC, glebfox commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/app/jmxconsole/MBeanInfoDetailView.java
> +        operationsSearchField.setSuffixComponent(searchIcon);
Same as  for list view

2023-08-27 16:28 UTC, glebfox commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/app/jmxconsole/MBeanInfoDetailView.java
> +    protected void initDatagridColumns() {
DataGrid

2023-08-27 16:28 UTC, glebfox commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/app/jmxconsole/MBeanOperationComposite.java
> +        operationVbox = uiComponents.create(VerticalLayout.class);
add blank lines between separate component for better readability

2023-09-05 14:30 UTC, breakingfox commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/app/jmxconsole/JmxConsoleView.java
> +        mbeanSearchField.addKeyPressListener(Key.ENTER, keyPressEvent -> reloadMBeans(mbeanSearchField.getValue()));
Dataloadcoordinator only works with loader query and not a loader delegate?

2023-09-15 10:38 UTC, gorbunkov requested changes
We decided to extract this add-on into a separate module. Please see the short and long add-on ids in the YouTrack document https://youtrack.haulmont.com/articles/PLAT-A-13/Jmix-Subsystems

2023-09-15 13:22 UTC, glebfox requested changes

2023-09-15 13:22 UTC, glebfox commented on jmix-flowui/flowui/src/main/resources/io/jmix/flowui/app/jmxconsole/mbean-detail-view.xml
> +        <dataGrid id="attributesDataGrid" dataContainer="attrDc" minHeight="20em" maxHeight="50em" width="100%">
Let's make it fixed size. Now it annoyingly changes its heigh.

2023-09-15 13:22 UTC, glebfox commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/app/jmxconsole/MBeanInfoDetailView.java
> +public class MBeanInfoDetailView extends StandardDetailView<ManagedBeanInfo> {
let's disable `PreventBrowserTabClosing`. All data is saved after change, so we won't lose anything.

2023-09-23 12:20 UTC, glebfox requested changes

2023-09-23 12:20 UTC, glebfox commented on jmix-translations/content/io/jmix/flowui/messages_ru.properties
> +io.jmix.jmxconsole/operationResult.caption=Результат операции
What about this key? Do you use it or `mbeanOperationResult.title` its replacement? Why `mbeanOperationResult.title` isn't translated to the other languages?

Check your localization keys and their usage

2023-09-23 12:20 UTC, glebfox commented on jmix-jmxconsole/jmxconsole/src/main/java/io/jmix/jmxconsole/JmxConsoleConfiguration.java
> +        viewControllers.setBasePackages(Collections.singletonList("io.jmix.jmxconsole"));
move all views to the `io.jmix.jmxconsole.view` package

2023-09-23 12:20 UTC, glebfox commented on jmix-jmxconsole/jmxconsole/src/main/java/io/jmix/jmxconsole/JmxConsoleConfiguration.java
> +        actions.setBasePackages(Collections.singletonList("io.jmix.jmxconsole"));
1. do you have actions?
2. Actions should be located in the `xxx.action` package, no need to make platform scan all the packages in the module to find actions.

2023-09-23 12:20 UTC, glebfox commented on jmix-jmxconsole/jmxconsole/src/main/resources/io/jmix/jmxconsole/mbean-detail-view.xml
> +        <dataGrid id="attributesDataGrid" dataContainer="attrDc" height="40em" width="100%">
1. don't you think that it's tooo much? 
2. For some reason the size doesn't work. Try to open mbean with and without attributes

2023-10-09 14:14 UTC, glebfox requested changes

2023-10-20 07:13 UTC, glebfox approved these changes

2023-10-20 12:28 UTC, merged