[DatePicker] support showWeekNumbers in XML jmix-framework/jmix#2092
jmix-framework/jmix pull request #2122
Opened 2023-08-07 12:59 UTC by KremnevDmitry

Related to: https://github.com/jmix-framework/jmix/issues/2092

2023-08-07 13:02 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/support/ComponentLoaderSupport.java
> +    protected void loadDateFormat(DatePicker.DatePickerI18n datePickerI18n, Element element) {
This method has become `protected`, do we accept such API changes?
It's kind of like more for internal use?

2023-08-17 12:53 UTC, glebfox requested changes

2023-08-18 06:48 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/support/ComponentLoaderSupport.java
> +    protected void loadDateFormat(DatePicker.DatePickerI18n datePickerI18n, Element element) {
So... will be marked as deprecated until the next minor release.

2023-08-18 07:53 UTC, glebfox approved these changes

2023-08-18 08:01 UTC, merged