Ability to define prefix and suffix components in XML jmix-framework/jmix#2096
jmix-framework/jmix pull request #2130
Opened 2023-08-09 09:23 UTC by KremnevDmitry

Studio issue: [JST-4191](https://youtrack.jmix.io/issue/JST-4191/Support-prefixsuffix-elements-in-XML)
Framework issue: jmix-framework/jmix#2096

### Problems: 

1. Prefomance issue for: io.jmix.flowui.component.UiComponentUtils#getComponentRecursively
2. Useless DrawerToggle implementation: see issue

2023-08-17 13:25 UTC, glebfox requested changes

2023-08-17 13:46 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/support/PrefixSuffixLoaderSupport.java
> +            createPrefixComponent(hasPrefixComponent, element);
Sure

2023-08-18 08:03 UTC, glebfox requested changes

2023-08-18 08:03 UTC, glebfox commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/support/PrefixSuffixLoaderSupport.java
>              throw new GuiDevelopmentException("Only one suffix component can be defined", context);
It seems that it's better to pass element name to the method so the exception text adapts to element name. Currently it's hardcoded `suffix`

2023-08-18 11:53 UTC, glebfox approved these changes

2023-08-18 11:58 UTC, merged