User substitution views #1006
jmix-framework/jmix pull request #2226
Opened 2023-09-12 09:25 UTC by KremnevDmitry

Issue: #1006

2023-09-18 08:04 UTC, glebfox requested changes

2023-09-18 09:36 UTC, KremnevDmitry commented on jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/main/UserIndicator.java
> +            hasValueComponent.setValue(user);
The `flowui` module is not available in the `flowui-kit` module

2023-09-18 10:00 UTC, KremnevDmitry commented on jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/action/ShowRoleAssignmentsAction.java
> +        this.text = messages.getMessage("actions.showRoleAssignments");
Do i need to create an issue?

2023-09-19 11:45 UTC, glebfox commented on jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/action/ShowRoleAssignmentsAction.java
> +        this.text = messages.getMessage("actions.showRoleAssignments");
nope

2023-09-19 11:46 UTC, glebfox approved these changes

2023-09-19 11:47 UTC, merged