Ability to define theme names for layouts jmix-framework/jmix#2285
jmix-framework/jmix pull request #2307
Opened 2023-10-03 12:22 UTC by KremnevDmitry

2023-10-04 11:15 UTC, glebfox approved these changes

2023-10-04 11:15 UTC, glebfox commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/Subscribe.java
> +     * @return property name that will be set using annotated method
what? isn't it explicit method name?

2023-10-04 11:25 UTC, glebfox requested changes
1. Test
2. `subject` should work for non method clash cases

2023-10-04 12:48 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/Subscribe.java
> +     * @return property name that will be set using annotated method
Fixed

2023-10-05 08:57 UTC, glebfox approved these changes

2023-10-06 05:34 UTC, merged