1844 trigger description is not localized. Fixed
jmix-framework/jmix pull request #2497
Opened 2023-11-20 16:40 UTC by fractal3000

2023-12-07 13:56 UTC, Gavrilov-Ivan requested changes

2023-12-07 13:56 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz/src/main/java/io/jmix/quartz/service/QuartzDescriptionService.java
> +    private static String calculateInterval(Long repeatInterval) {
Думаю лучше назвать в стиле `formatToSeconds` или как-то похоже. Вычисления интервала там по сути не происходит.

2023-12-07 13:56 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz/src/main/java/io/jmix/quartz/service/QuartzDescriptionService.java
> +        double doubleValue = (double) repeatInterval / 1000;
`repeatInterval` формально nullable, хотя эффективно (при Simple Schedule типе расписания) null быть не должно.
Но чтобы не было никаких warning'ов - добавь проверку на null с исключением.

2023-12-07 13:56 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz/src/main/java/io/jmix/quartz/service/QuartzDescriptionService.java
> +    public String getScheduleDescription(JobModel jobModel) {
Nullable

2023-12-07 13:56 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz/src/test/java/io/jmix/quartz/service/QuartzDescriptionServiceTest.java
> +        String cronExpression = "Some CRON expression";
Минорно: напиши реальное cron выражение (в других тестах тоже)

2023-12-07 13:56 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz/src/test/java/io/jmix/quartz/service/QuartzDescriptionServiceTest.java
> +    void getScheduleDescription_simple_schedule_type_less_1_second_interval(long interval, String formattedInterval) {
Название. Судя по параметрам, данный тест проверяет не только случаи <1000ms

2023-12-07 13:56 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz/src/test/java/io/jmix/quartz/service/QuartzDescriptionServiceTest.java
> +                .thenReturn("Execute once message");
Убери 'message' - пусть совпадает реальным сообщением

2023-12-07 13:56 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz/src/test/java/io/jmix/quartz/service/QuartzDescriptionServiceTest.java
> +                .thenReturn("Execute once message");
А почему тут 'Execute once', если тест на множественные повторения?
На функционирование теста само сообщение не влияет, но для наглядности сделай то, что ожидается в реальности.

2023-12-07 13:56 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz/src/test/java/io/jmix/quartz/service/QuartzDescriptionServiceTest.java
> +                .thenReturn("Execute forever every 10 seconds");
Вынеси ожидаемое сообщение в переменную (в других тестах тоже)

2023-12-07 13:56 UTC, Gavrilov-Ivan commented on jmix-translations/content/io/jmix/quartz/messages.properties
> +io.jmix.quartz.service/ExecuteForeverMessage=Execute forever every %s seconds
camelCase

2023-12-07 13:56 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz-flowui/src/main/java/io/jmix/quartzflowui/view/jobs/JobModelListView.java
> +        triggerDescriptionColumn.setHeader(messageBundle.getMessage("column.triggerDescription.header"));
"column.triggerScheduleDescription.header"

2023-12-07 13:56 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz-flowui/src/main/java/io/jmix/quartzflowui/view/jobs/JobModelDetailView.java
> +                .setHeader(messageBundle.getMessage("column.scheduleDescription.header"));
"column.jobScheduleDescription.header" (и в messages соответственно)

2023-12-07 13:56 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz-flowui/src/main/resources/io/jmix/quartzflowui/messages.properties
> +io.jmix.quartzflowui.view.jobs/column.triggerDescription.header=Trigger description
Schedule description

2023-12-07 13:56 UTC, Gavrilov-Ivan commented on jmix-translations/content/io/jmix/quartzflowui/messages.properties
> +io.jmix.quartzflowui.view.jobs/column.scheduleDescription.header=Description
Локализацию обнови согласно изменениям в "модульных" messages-файлах

2023-12-07 14:35 UTC, Gavrilov-Ivan requested changes

2023-12-07 14:35 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz/src/main/java/io/jmix/quartz/service/QuartzDescriptionService.java
> +public class QuartzDescriptionService {
`ScheduleDescriptionService` думаю будет лучше

2023-12-07 14:38 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz/src/main/java/io/jmix/quartz/service/QuartzDescriptionService.java
> +@Service("quartz_QuartzDescriptionService")
Javadoc

2023-12-08 06:25 UTC, fractal3000 commented on jmix-quartz/quartz-flowui/src/main/java/io/jmix/quartzflowui/view/jobs/JobModelListView.java
> +    private String getHeaderForColumn(String propertyName) {
Хорошо

2023-12-08 06:36 UTC, fractal3000 commented on jmix-quartz/quartz-flowui/src/main/resources/io/jmix/quartzflowui/messages.properties
> +io.jmix.quartzflowui.view.jobs/column.triggerDescription.header=Trigger description
Уже изменено в соответствии с предыдущими комментариями

2023-12-11 14:05 UTC, Gavrilov-Ivan requested changes

2023-12-11 21:18 UTC, fractal3000 commented on jmix-quartz/quartz-flowui/src/main/java/io/jmix/quartzflowui/view/jobs/JobModelListView.java
> +    private String getHeaderForColumn(String propertyName) {
Готово

2023-12-11 21:20 UTC, fractal3000 commented on jmix-quartz/quartz-flowui/src/main/resources/io/jmix/quartzflowui/messages.properties
> +io.jmix.quartzflowui.view.jobs/column.scheduleDescription.header=Description
Константа переименована
io.jmix.quartzflowui.view.jobs/column.jobScheduleDescription.header=Schedule description

2023-12-11 21:21 UTC, fractal3000 commented on jmix-quartz/quartz/src/main/java/io/jmix/quartz/service/QuartzDescriptionService.java
> +    static final String EXECUTE_FOREVER_MESSAGE_KEY = "ExecuteForeverMessage";
готово

2023-12-11 21:21 UTC, fractal3000 commented on jmix-quartz/quartz/src/main/java/io/jmix/quartz/service/QuartzDescriptionService.java
> +    protected Messages messages;
Готово

2023-12-11 21:22 UTC, fractal3000 commented on jmix-quartz/quartz/src/main/java/io/jmix/quartz/service/QuartzDescriptionService.java
> +            return null;
Готово

2023-12-11 21:26 UTC, fractal3000 commented on jmix-quartz/quartz/src/main/java/io/jmix/quartz/service/QuartzDescriptionService.java
> +    private static String calculateInterval(Long repeatInterval) {
Назвал getFormattedSeconds. Вроде бы немного ближе по смыслу.

2023-12-11 21:45 UTC, fractal3000 commented on jmix-quartz/quartz/src/main/java/io/jmix/quartz/service/QuartzDescriptionService.java
> +        double doubleValue = (double) repeatInterval / 1000;
Можно было бы валидацию написать, используя BeanValidation, чтобы проверялась корректность данных на уровне модели(т.е. если тип триггера "Simple", то наличие параметра repeatInterval обязательно). Добавил проверку с выдачей исключения об ошибке(IllegalStateException) и соответствующий модульный тест.

2023-12-11 21:45 UTC, fractal3000 commented on jmix-quartz/quartz/src/main/java/io/jmix/quartz/service/QuartzDescriptionService.java
> +    public String getScheduleDescription(JobModel jobModel) {
Готово

2023-12-11 21:53 UTC, fractal3000 commented on jmix-quartz/quartz/src/test/java/io/jmix/quartz/service/QuartzDescriptionServiceTest.java
> +    void getScheduleDescription_simple_schedule_type_less_1_second_interval(long interval, String formattedInterval) {
Поправил.

2023-12-11 22:01 UTC, fractal3000 commented on jmix-quartz/quartz/src/test/java/io/jmix/quartz/service/QuartzDescriptionServiceTest.java
> +                .thenReturn("Execute once message");
Исправил

2023-12-11 22:09 UTC, fractal3000 commented on jmix-quartz/quartz/src/test/java/io/jmix/quartz/service/QuartzDescriptionServiceTest.java
> +                .thenReturn("Execute forever every 10 seconds");
Готово

2023-12-11 22:11 UTC, fractal3000 commented on jmix-quartz/quartz-flowui/src/main/java/io/jmix/quartzflowui/view/jobs/JobModelListView.java
> +        triggerDescriptionColumn.setHeader(messageBundle.getMessage("column.triggerDescription.header"));
Изменил на column.jobScheduleDescription.header

2023-12-11 22:12 UTC, fractal3000 commented on jmix-quartz/quartz-flowui/src/main/java/io/jmix/quartzflowui/view/jobs/JobModelDetailView.java
> +                .setHeader(messageBundle.getMessage("column.scheduleDescription.header"));
Заменил на column.triggerScheduleDescription.header

2023-12-12 13:34 UTC, Gavrilov-Ivan approved these changes

2023-12-12 13:34 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz/src/test/java/io/jmix/quartz/util/ScheduleDescriptionProviderTest.java
> +    void getScheduleDescription_simple_schedule_type_negative_repeat_count() {
В названии negative - уже неактуально

2023-12-12 20:13 UTC, fractal3000 commented on jmix-quartz/quartz/src/test/java/io/jmix/quartz/util/ScheduleDescriptionProviderTest.java
> +    void getScheduleDescription_simple_schedule_type_negative_repeat_count() {
Иван, спасибо, что обратил внимание на название. В последний раз по ошибке(мне показалось, что за ненадобностью) удалил всё, что связано с repeatCount. Сейчас посмотрел внимательнее. Этот тест был специально сделан для тестирования вот этого условия
`        if (Objects.isNull(repeatCount) || repeatCount < 0) {
`
в методе io.jmix.quartz.util.ScheduleDescriptionProvider#getScheduleDescription(io.jmix.quartz.model.TriggerModel).

Откатил изменения этого тестового метода до предыдущего состояния. Теперь всё в порядке. Название оставил прежнее, потому что оно дейсвительно тестирует случай с отрицательными repeatCount.

Для случая, когда repeatCount == null есть( и был) отдельный тестовый метод getScheduleDescription_simple_schedule_type_null_repeat_count

2023-12-12 20:18 UTC, merged