Sorting issue on WebDAV documents view#2396
jmix-framework/jmix pull request #2533
Opened 2023-11-30 10:30 UTC by fractal3000

2023-12-14 10:59 UTC, Gavrilov-Ivan requested changes

2023-12-14 10:59 UTC, Gavrilov-Ivan commented on jmix-translations/content/io/jmix/webdavflowui/messages_ru.properties
> +io.jmix.webdavflowui.view.webdavdocument/invalidPath=Неверный путь "%s"
Возможно тут лучше подойдет "Недопустимый", т.е. ввели что-то кривое в принципе. А про "неверный" можно подумать, что он ведет на то, чего нет, а это уже not found случай.

2023-12-19 22:10 UTC, fractal3000 commented on jmix-translations/content/io/jmix/webdavflowui/messages_ru.properties
> +io.jmix.webdavflowui.view.webdavdocument/invalidPath=Неверный путь "%s"
Исправил.

2023-12-26 15:55 UTC, Gavrilov-Ivan approved these changes

2023-12-26 15:56 UTC, merged