DatePicker doesn't localize its popup #2444
jmix-framework/jmix pull request #2549
Opened 2023-12-04 06:57 UTC by breakingfox

2023-12-18 09:27 UTC, glebfox requested changes

2023-12-18 09:27 UTC, glebfox commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/DateInternationalizationHelper.java
> +                .collect(Collectors.toList());
Can be simplified to `toList()` as you did in the method above.

2023-12-18 09:27 UTC, glebfox commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/DateInternationalizationHelper.java
> +public class DateInternationalizationHelper {
This helper class requires tests

2023-12-27 08:02 UTC, glebfox approved these changes

2023-12-27 08:03 UTC, NikitaShchienko approved these changes

2023-12-27 08:08 UTC, merged