fix Unique constraint violation is not handled correctly when using l…
jmix-framework/jmix pull request #2680
Opened 2023-12-22 13:45 UTC by KartnDev

…atest MS SQLServer #2324

2023-12-25 10:14 UTC, gorbunkov requested changes

2023-12-25 10:14 UTC, gorbunkov commented on jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/dbms/SqlServerDbmsFeatures.java
> +        return "(Violation of UNIQUE KEY constraint '(.+?)'|with unique index '(.+)')";
This pattern doesn't work as expected. 

Please read the issue description again and compare your result with the expected one:

> ER:
Notification "A department with the same name already exists"

See docs: https://docs.jmix.io/jmix/flow-ui/exception-handlers.html#unique-constraint-violation-handler

2023-12-26 19:54 UTC, KartnDev commented
## Before (2 groups bug)
### Regex was:
`(Violation of UNIQUE KEY constraint '(.+?)'|with unique index '(.+)')`

* **If matching** `somewith sad sa as d with unique index 'ASDSAD_ASDSADSAD'`:
    * **1 group**: with unique index 'ASDSAD_ASDSADSAD'
    * **2 group**: ASDSAD_ASDSADSAD
* **If matching** `Violation of UNIQUE KEY constraint ASD_ASDSADS_ADSADASDSAD'`:
    * **1 group**: Violation of UNIQUE KEY constraint 'ASD_ASDSADS_ADSADASDSAD'
    * **2 group**: ASD_ASDSADS_ADSADASDSAD
    
![image](https://github.com/jmix-framework/jmix/assets/43281522/7401ddb8-cc54-4047-993b-6bf0323095b3)
## After (bracket group escape)
### Regex was:
`Violation of UNIQUE KEY constraint '(.+?)'|with unique index '(.+)'` => **REMOVED () root regex group**

* **If matching** `somewith sad sa as d with unique index 'ASDSAD_ASDSADSAD'`:
    * **1 group**: ASDSAD_ASDSADSAD
* **If matching** `Violation of UNIQUE KEY constraint ASD_ASDSADS_ADSADASDSAD'`:
    * **1 group**: ASD_ASDSADS_ADSADASDSAD

![image](https://github.com/jmix-framework/jmix/assets/43281522/0ae06804-ce72-489c-9201-ef460a10524d)
## Solved problem:
I created 2 groups, so internal component sees that the first group givin not-null string and interpret it as contstraint name

2023-12-27 08:33 UTC, gorbunkov approved these changes

2023-12-27 09:43 UTC, merged