Fix that the name in the generated Code field does not start with a capital letter
jmix-framework/jmix pull request #2751
Opened 2024-01-16 12:51 UTC by KartnDev

I choose to concate category name and attribute name by **_** instead of trying to predict which case user chose for name:
samples:
1. How to concate when category name is FULLUPPERCASE or fULLCASEWITHUNDERCUT
2. Same as first but for attribute name

Besides, we can do not change names and just concate both with "_" and we will prevent any misunderstood cases

2024-01-18 08:32 UTC, gorbunkov commented
@KartnDev 

> How to concate when category name is FULLUPPERCASE or fULLCASEWITHUNDERCUT

First of all, let's stick to real-life cases. 99.9% of users won't write a category or attribute name this way. They will do smth like:
* Some nice category
* some nice category
* someNiceCategory
* SomeNiceCategory
* some_nice_category (also possible)

The same for attribute name.

I agree with your arguments about readability, but on the other hand I would prefer that the code of the dynamic attribute looks like any other entity attribute name (we see them in metamodel, in REST API, etc.). We usually start entity attribute names with the lowercase and use camelCase. If dynamic attributes looked the same they, that would be the best choice, in my opinion:

Car
* vin
* productionDate
* +someCarCategorySomeAttributeName

So, what I would do while building an attribute code:

* convert both a category and a name to the camel case (e.g. by using `org.apache.commons.text.CaseUtils#toCamelCase`)
* start category name with the lowercase letter 
* start attribute name with the uppercase letter
* concatenate them

"Some car category"."some attribute" -> "someCarCategorySomeAttribute"

2024-01-18 08:32 UTC, gorbunkov requested changes
See my comment https://github.com/jmix-framework/jmix/pull/2751#issuecomment-1898019429
WDYT?

2024-01-19 11:07 UTC, gorbunkov requested changes
Could you please re-read my comment again and try the example that is written there:

```
"Some car category"."some attribute" -> "someCarCategorySomeAttribute"
```

Your solution works differently

2024-01-19 12:08 UTC, KartnDev commented
> some attribute

![image](https://github.com/jmix-framework/jmix/assets/43281522/0ae5ce21-1670-4bf4-a14e-6dd489a36586)
![image](https://github.com/jmix-framework/jmix/assets/43281522/142c8b7a-f9d2-4003-970a-4fa54cdd92dd)

2024-01-19 14:22 UTC, gorbunkov approved these changes

2024-01-19 14:22 UTC, gorbunkov commented on jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/view/categoryattr/CategoryAttributesDetailView.java
> +            String resultCodeName = org.springframework.util.StringUtils.hasText(categoryNameInCamelCaseUncapitalized) ?
In framework code we mostly use Guava `com.google.common.base.Strings#isNullOrEmpty` for that

2024-01-19 16:10 UTC, merged