absent changes 2595
jmix-framework/jmix pull request #2763
Opened 2024-01-17 15:20 UTC by syncro

2024-01-17 15:35 UTC, Gavrilov-Ivan requested changes
А где QuartzExceptionHandler?

2024-01-17 15:35 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz-flowui/src/main/java/io/jmix/quartzflowui/view/jobs/JobModelDetailView.java
> +    protected Notifications notifications;
Эти 2 сервиса более не используются?

2024-01-17 15:35 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz/src/main/java/io/jmix/quartz/service/QuartzService.java
> -    @Transactional(rollbackForClassName={"Exception"})
Почему удаляем? Ошибка мержа?

2024-01-17 15:42 UTC, syncro commented on jmix-quartz/quartz-flowui/src/main/java/io/jmix/quartzflowui/view/jobs/JobModelDetailView.java
> +    protected Notifications notifications;
похоже на то, но они есть в мастере

2024-01-17 15:51 UTC, Gavrilov-Ivan commented on jmix-quartz/quartz-flowui/src/main/java/io/jmix/quartzflowui/view/jobs/JobModelDetailView.java
> +    protected Notifications notifications;
Ну значит и в мастере им нечего делать.

2024-01-17 16:27 UTC, syncro commented on jmix-quartz/quartz-flowui/src/main/java/io/jmix/quartzflowui/view/jobs/JobModelDetailView.java
> +    protected Notifications notifications;
убрал в мр на мастер

2024-01-17 16:29 UTC, syncro commented on jmix-quartz/quartz/src/main/java/io/jmix/quartz/service/QuartzService.java
> -    @Transactional(rollbackForClassName={"Exception"})
исправил

2024-01-18 08:40 UTC, Gavrilov-Ivan approved these changes

2024-01-18 08:46 UTC, merged