bug/1763-email-history-table-content-isnt-fully-visible
jmix-framework/jmix pull request #2843
Opened 2024-02-05 13:08 UTC by ilushaaa

#1763

According to the issue we cannot change column width. But in the current version we able to change column width and order.
As small improvement I added settings facet to save user preferences for the dataGrid.

2024-02-05 14:31 UTC, glebfox commented
As Max's suggest in the [comment](https://github.com/jmix-framework/jmix/issues/1763#issuecomment-1867352717):
> We need to add columns resize, column collapsing and set autoSize

2024-02-05 14:38 UTC, glebfox requested changes

2024-02-05 14:38 UTC, glebfox commented on jmix-email/email-flowui/src/main/resources/io/jmix/emailflowui/view/sendingmessage/sending-message-view.xml
> +        <settings>
take a look at how we can define autoSize for the DatGrid columns + at this [issue](https://github.com/jmix-framework/jmix/issues/1925).

2024-02-06 09:14 UTC, ilushaaa commented
gridColumnVisibility component was added.
All columns got autoWidth attribute except subject, bodyContentType and attachments.

2024-02-07 07:53 UTC, glebfox requested changes

2024-02-07 07:53 UTC, glebfox commented on jmix-email/email-flowui/src/main/resources/io/jmix/emailflowui/messages.properties
> +io.jmix.emailflowui.view.sendingmessage/sendingMessageView.sendingMessageDataGrid.columnVisibility = Show/Hide Columns
don't forget that we have other languages, see `jmix-translations` module

2024-02-07 07:53 UTC, glebfox commented on jmix-email/email-flowui/src/main/resources/io/jmix/emailflowui/view/sendingmessage/sending-message-view.xml
> -        <settings>
it's better to keep settings facet, otherwise changing column sizes and collapsing them won't persist

2024-02-07 07:53 UTC, glebfox commented on jmix-email/email-flowui/src/main/resources/io/jmix/emailflowui/view/sendingmessage/sending-message-view.xml
> +                        <menuItem refColumn="address"/>
Are you sure that you need explicitly define each column?

2024-02-07 07:53 UTC, glebfox commented on jmix-email/email-flowui/src/main/resources/io/jmix/emailflowui/view/sendingmessage/sending-message-view.xml
>                          <column property="cc"/>
why not setting `autoWidth` for CC and BCC? their content is cut off

2024-02-07 07:53 UTC, glebfox commented on jmix-email/email-flowui/src/main/resources/io/jmix/emailflowui/view/sendingmessage/sending-message-view.xml
> +                        <column property="subject" width="300px"/>
We don't use `px`. `em` is preferable

2024-02-07 07:53 UTC, glebfox commented on jmix-email/email-flowui/src/main/resources/io/jmix/emailflowui/view/sendingmessage/sending-message-view.xml
> +                        <column property="bodyContentType" width="180px"/>
Due to the number of columns we have horizontal scrolling. Does it make sense to truncate the content type value?

2024-02-08 07:52 UTC, glebfox approved these changes

2024-02-08 10:01 UTC, merged