Change logics for code generation for code attributes #2570
jmix-framework/jmix pull request #2851
Opened 2024-02-06 14:50 UTC by KartnDev

![image](https://github.com/jmix-framework/jmix/assets/43281522/4f2284a5-0937-4b4a-a06e-728a4e63c716)

2024-02-08 12:24 UTC, gorbunkov requested changes

2024-02-08 12:24 UTC, gorbunkov commented on jmix-dynattr/dynattr/src/main/java/io/jmix/dynattr/utils/DynAttrStringUtils.java
> +     * @apiNote This method is designed to prevent unintentional conversion of camelCase or PascalCase strings into lowercase.
What's the purpose of the `@apiNote` tag? I never saw it and I don't get why not to write this text as a new paragraph?

2024-02-08 12:24 UTC, gorbunkov commented on jmix-dynattr/dynattr/src/main/java/io/jmix/dynattr/utils/DynAttrStringUtils.java
> +
Too many empty lines between methods

2024-02-08 12:24 UTC, gorbunkov commented on jmix-dynattr/dynattr/src/test/groovy/dynamic_attributes/DynAttrStringUtilsTest.groovy
> +class DynAttrStringUtilsTest extends Specification {
I don't see tests for input that consists of several words, e.g. "Some text" -> someText or "some text" -> someText

2024-02-12 20:23 UTC, KartnDev commented
Add "space cases" tests
![image](https://github.com/jmix-framework/jmix/assets/43281522/f19c93df-5e28-4ee3-8525-73b2ee7ad35d)

2024-02-13 06:03 UTC, gorbunkov requested changes

2024-02-13 06:03 UTC, gorbunkov commented on jmix-dynattr/dynattr/src/test/groovy/dynamic_attributes/DynAttrStringUtilsTest.groovy
> +        String pascalCaseString = "Space case String"
All such variables in all tests are called `pascalCaseString` that doesn't seem correct. Rename these variables.

2024-02-14 10:48 UTC, gorbunkov approved these changes

2024-02-14 16:41 UTC, merged