Data binding for HTML components 3288
jmix-framework/jmix pull request #3400
Opened 2024-06-18 16:52 UTC by ilushaaa

#3288

2024-06-19 06:49 UTC, KremnevDmitry requested changes

2024-06-19 06:49 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/data/binding/impl/HtmlContainerReadonlyDataBindingImpl.java
> +            }
![image](https://github.com/jmix-framework/jmix/assets/75516667/5f681a02-9f30-4ea8-9bf0-2cb2483dc6e5)


Java 17 baby:
```suggestion
            if (value instanceof Collection<?> collectionValue) {
                return formatCollection(collectionValue);
            }
```

2024-06-19 06:49 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/html/AbstractHtmlContainerLoader.java
> +        }
1. I'm sure we should move this into a separate `loadData(resultComponent, element)` method.
2. Unnecessary variable `instanceContainer` it seems:

```suggestion
getDataLoaderSupport().loadContainer(element, property)
            .ifPresent(container -> getHtmlDataBinding().bind(resultComponent, container, property));
```

3. Result component can be null? WAT? 54 line

2024-06-19 06:49 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/test/groovy/data_binding_html_container/HtmlContainerReadonlyDataBindingTest.groovy
> +class HtmlContainerReadonlyDataBindingTest extends FlowuiTestSpecification {
I think we should write one more test for a HTML component that only has a `property` attribute, and this HTML component should be located in a `formLayout` in which the `dataContainer` is specified

2024-06-19 06:49 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/html/AbstractHtmlContainerLoader.java
> +            htmlComponentReadonlyDataBinding = applicationContext.getBean(HtmlContainerReadonlyDataBinding.class, context);
You don't need to pass the `context` as an additional variable
`DataLoaderSupport` bean requires `context` as a constructor argument

In the `HtmlContainerReadonlyDataBinding` constructor, you are requests for a bean, which will autowired automatically
There's definitely no need for context there

```suggestion
            htmlComponentReadonlyDataBinding = applicationContext.getBean(HtmlContainerReadonlyDataBinding.class);
```

2024-06-19 06:49 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/data/binding/impl/HtmlContainerReadonlyDataBindingImpl.java
> +    protected List<Pair<HtmlContainer, HtmlContainerListenerRegistrationsCleaner>> listenersRegistrations = new LinkedList<>();
More than 120 characters per line

List of a pairs... Maybe we need to use Map?

2024-06-19 06:49 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/data/binding/impl/HtmlContainerReadonlyDataBindingImpl.java
> +            updateHtmlContainerText(htmlContainer, formatter, valueChangeEvent.getValue()));
Not aligned (ALT-CTRL-L)

2024-06-19 06:49 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/data/binding/impl/HtmlContainerReadonlyDataBindingImpl.java
> +    protected interface HtmlContainerListenerRegistrationsCleaner {
We don't need this, we can use `com.vaadin.flow.shared.Registration`

2024-06-19 06:49 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/data/binding/impl/HtmlContainerReadonlyDataBindingImpl.java
> +    public void bind(HtmlContainer htmlComponent, ValueSource<?> valueSource) {
What happens if I try to bind a component to one container and then to another one?

I don't see a way to automatically unbind a container if it has already been bound to any one.
I think that's why we should use a map to persist subscriptions.

Then, when we try to bind a new container, we will have to unbind the old one, write in the log that we unbind
And bind a new one
See `io.jmix.flowui.component.delegate.AbstractValueComponentDelegate#setValueSource` as a source of inspiration

2024-06-19 06:49 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/data/binding/impl/HtmlContainerReadonlyDataBindingImpl.java
> +        Preconditions.checkNotNullArgument(formatter);
We use this quite often, maybe we need static import?

2024-06-19 06:49 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/data/binding/impl/HtmlContainerReadonlyDataBindingImpl.java
> +    class HtmlContainerTextFormatter implements Formatter<Object> {
I don't like the concept of a non-static class that uses one `MetadataTools` bean from its parent
I think we should remove it

Moreover, the parent class doesn't use the bean at all O_O

You have a clear division between collection binding and instance binding
For collection binding, you can use the ready-made `io.jmix.flowui.component.formatter.CollectionFormatter`
And for a instance one, you can simply use a lambda with `MetadataTools#apply`

2024-06-19 11:08 UTC, KremnevDmitry requested changes

2024-06-19 11:08 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/data/binding/impl/HtmlContainerReadonlyDataBindingImpl.java
> +    protected List<Pair<HtmlContainer, DataBindingListenerCleaner>> listenersRegistrations = new LinkedList<>();
Use `Map<HtmlContainer, Runnable>`

2024-06-19 11:08 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/data/binding/impl/HtmlContainerReadonlyDataBindingImpl.java
> +        listenersRegistrations.add(new Pair<>(htmlContainer, itemChangeCleaner));
When `list` will be replaced to `map` the following code will be applicable

```java
        listenersRegistrations.put(htmlContainer, () -> {
            propertyChangeSubscription.remove();
            itemChangeSubscription.remove();
        });
```

2024-06-19 11:08 UTC, KremnevDmitry commented on jmix-flowui/flowui/src/main/java/io/jmix/flowui/data/binding/impl/HtmlContainerReadonlyDataBindingImpl.java
> +        }
When `list` will be replaced to `map` then you can simply use the following construction here:

```suggestion
        Runnable remove = listenersRegistrations.get(htmlContainer);
        if (remove == null) {
            return;
        }

        remove.run();
        listenersRegistrations.remove(htmlContainer);
        
        if (warnIfBound) {
            log.warn("Silent unbind. HtmlContainer with id = '{}' was already bounden with data source.",
                    htmlContainer.getId());
        }
```

2024-06-19 12:55 UTC, KremnevDmitry approved these changes
Allowed to review by GG after aligning the lines and checking security permissions

2024-07-01 10:25 UTC, glebfox requested changes

2024-07-31 13:37 UTC, glebfox approved these changes

2024-08-02 07:38 UTC, merged