Implement putMapping operation for incremental index mapping updates inside search add-on #3218
jmix-framework/jmix pull request #3565
Opened 2024-08-13 11:05 UTC by fractal3000

2024-09-04 11:30 UTC, Gavrilov-Ivan requested changes

2024-09-04 11:30 UTC, Gavrilov-Ivan commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexMappingComparator.java
> +        CAN_BE_UPDATED,
UPDATABLE

2024-09-04 11:30 UTC, Gavrilov-Ivan commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexMappingComparator.java
> +        public boolean indexRecreatingIsRequired() {
rename: is...

2024-09-04 11:30 UTC, Gavrilov-Ivan commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexSettingsComparator.java
> +    protected abstract   IndexSettingsType extractAppliedIndexSettings(IndexSettingsType allAppliedSettings);
fix

2024-09-04 11:30 UTC, Gavrilov-Ivan commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexSettingsComparator.java
> +        IndexSettingsType allAppliedSettings = extractAllAppliedIndexSettings(currentIndexState);
nullable

2024-09-04 11:30 UTC, Gavrilov-Ivan commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexSettingsComparator.java
> +        IndexSettingsType appliedIndexSettings = extractAppliedIndexSettings(allAppliedSettings);
squash settings extraction

2024-09-05 07:44 UTC, fractal3000 commented on jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/impl/ElasticsearchIndexManager.java
> +public class ElasticsearchIndexManager extends BaseIndexManager<ElasticsearchClient, IndexState, IndexSettings, JsonpSerializable>{
Fixed

2024-09-05 08:03 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/BaseIndexManager.java
> +public abstract class BaseIndexManager<ClientType, IndexStateType, IndexSettingsType, JsonpSerializableType> implements IndexManager {
Fixed

2024-09-05 08:09 UTC, fractal3000 commented on jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/impl/ElasticsearchIndexManager.java
> +    private final ElasticsearchPutMappingService putMappingService;
fixed

2024-09-05 12:51 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexMappingComparator.java
> +    private static final Logger log = LoggerFactory.getLogger(IndexMappingComparator.class);
Fixed

2024-09-05 12:51 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexMappingComparator.java
> +    protected final TypeReference<Map<String, Object>> MAP_TYPE_REF = new TypeReference<>() {
fixed

2024-09-05 12:51 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexMappingComparator.java
> +    private final JsonpSerializer<JsonpSerializableType, ClientType> jsonpSerializer;
fixed

2024-09-05 12:52 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexMappingComparator.java
> +    public MappingComparingResult compare(IndexConfiguration indexConfiguration, IndexStateType currentIndexState, ClientType client) {
fixed

2024-09-05 12:55 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexMappingComparator.java
> +    private Map<String, Object> getAppliedMapping(IndexStateType currentIndexState, ClientType client) {
fixed

2024-09-05 13:00 UTC, fractal3000 commented on jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/impl/ElasticsearchMetadataResolver.java
> +    protected Map<String, IndexState> getIndexMetadataMapInternal(String indexName, ElasticsearchClient client) {
Fixed

2024-09-05 14:01 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/IndexSchemaManagementStrategy.java
> +    public boolean isIndexCreationSupported(){
fixed

2024-09-05 14:05 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/BaseIndexManager.java
>      protected IndexSynchronizationStatus handleIrrelevantIndex(IndexConfiguration indexConfiguration, IndexSchemaManagementStrategy strategy) {
fixed

2024-09-05 14:10 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/BaseIndexManager.java
> +            throw new IllegalStateException("Only index mapping update is supported currently");
It seems that the message is correct.

2024-09-05 14:16 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexConfigurationComparator.java
> +            IndexSettingsComparator<IndexStateType, IndexSettingsType,ClientType, JsonpSerializableType> settingsComparator, MetadataResolver<ClientType, IndexStateType, JsonpSerializableType> metada
Fixed

2024-09-05 14:17 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexConfigurationComparator.java
> +    private final IndexMappingComparator<IndexStateType, JsonpSerializableType, ClientType> mappingComparator;
Fixed

2024-09-05 14:20 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexConfigurationComparator.java
> +    public ConfigurationComparingResult compareConfigurations(IndexConfiguration indexConfiguration, ClientType client) {
Fixed

2024-09-05 14:21 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexConfigurationComparator.java
> +
Fixed

2024-09-05 14:22 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexMappingComparator.java
> +    private static Map<String, Object> getFilteredMapping(Map<String, Object> searchIndexMapping) {
Fixed

2024-09-05 14:27 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexMappingComparator.java
> +        public boolean indexRecreatingIsRequired() {
Fixed

2024-09-05 14:27 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexSettingsComparator.java
> +    protected abstract   IndexSettingsType extractAppliedIndexSettings(IndexSettingsType allAppliedSettings);
Fixed

2024-09-05 14:27 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexSettingsComparator.java
> +        IndexSettingsType appliedIndexSettings = extractAppliedIndexSettings(allAppliedSettings);
Fixed

2024-09-05 14:28 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/JsonNodesComparator.java
> +    protected boolean nodeContains(ObjectNode containerNode, ObjectNode contentNode) {
Fixed

2024-09-05 14:37 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexMappingComparator.java
> +        CAN_BE_UPDATED,
fixed

2024-09-05 14:47 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexMappingComparator.java
> +        for (Map.Entry<String, Object> mapEntry : filteredSearchIndexMapping.entrySet()) {
Fixed

2024-09-05 14:47 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/MappingFieldComparator.java
> +    public IndexMappingComparator.MappingComparingResult compareLeafFields(@NotNull Map<String, Object> searchIndexMapping, @NotNull Map<String, Object> applicationMapping) {
Fixed

2024-09-05 16:18 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/MetadataResolver.java
> +    public ObjectNode getIndexMetadata(String indexName, ClientType client) {
Fixed

2024-09-05 16:18 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/MetadataResolver.java
> +    public ObjectNode getIndexMetadata(String indexName, ClientType client) {
Fixed

2024-09-05 16:21 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/BaseIndexManager.java
> +        if (strategy.isIndexCreationSupported()) {
Fixed

2024-09-05 16:23 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexMappingComparator.java
> +    MappingComparingResult compare(Map<String, Object> searchIndexMapping, Map<String, Object> applicationMapping) {
Fixed

2024-09-05 16:24 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexSettingsComparator.java
> +        IndexSettingsType appliedIndexSettings = extractAppliedIndexSettings(allAppliedSettings);
Fixed

2024-09-05 16:24 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexSettingsComparator.java
> +        public boolean indexRecreatingIsRequired() {
Fixed

2024-09-05 16:25 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/JsonNodesComparator.java
> +    protected boolean nodeContains(ObjectNode containerNode, ObjectNode contentNode) {
Fixed

2024-09-05 16:25 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/MappingFieldComparator.java
> +    public IndexMappingComparator.MappingComparingResult compareLeafFields(@NotNull Map<String, Object> searchIndexMapping, @NotNull Map<String, Object> applicationMapping) {
Fixed

2024-09-05 16:25 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/PutMappingService.java
> +public interface PutMappingService<PutMappingRequestType, JsonpMapperType> {
Fixed

2024-09-11 08:46 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/BaseIndexManager.java
> +            throw new IllegalStateException("Only index mapping update is supported currently");
Fixed

2024-09-25 11:16 UTC, Gavrilov-Ivan requested changes

2024-09-25 11:16 UTC, Gavrilov-Ivan commented on jmix-search/search-opensearch/src/main/java/io/jmix/searchopensearch/index/impl/OpenSearchPutMappingRequestBuilder.java
> +            throw new RuntimeException(MAPPING_CONFIGURATION_PARSING_EXCEPTION_TEXT, e);
What index/entity

2024-09-25 11:16 UTC, Gavrilov-Ivan commented on jmix-search/search/src/main/java/io/jmix/search/index/IndexManager.java
> +     * @param mapping   - mapping for saving to configuration of the specified index
Remove hyphens.

Check other places

2024-09-25 11:16 UTC, Gavrilov-Ivan commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/JsonNodesComparator.java
> + * Compares two JSon nodes that contains index settings or index mapping in correspondence to such comparison rules.
JSON

2024-09-25 11:16 UTC, Gavrilov-Ivan commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/MappingComparingResult.java
> +    EQUAL,
Add empty line

2024-09-25 11:16 UTC, Gavrilov-Ivan commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/JsonpSerializer.java
> +    ObjectNode toObjectNode(TJsonp object);
Add empty line

2024-09-25 11:16 UTC, Gavrilov-Ivan commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/MappingFieldComparator.java
> + *
Fill or remove

2024-09-25 11:16 UTC, Gavrilov-Ivan commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/MappingFieldComparator.java
>      public static final String TYPE_KEY = "type";
Add empty line

2024-09-25 11:16 UTC, Gavrilov-Ivan commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/PutMappingBuilder.java
> +    TRequest buildRequest(IndexMappingConfiguration mappingConfiguration, String indexName, TJsonp jsonpMapper);
Add empty line

2024-09-27 07:55 UTC, fractal3000 commented on jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/impl/ElasticsearchIndexManager.java
> +    private final ElasticsearchClient client;
Should it be not final?

2024-09-27 12:30 UTC, fractal3000 commented on jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/impl/ElasticsearchIndexManager.java
> +    private final ElasticsearchClient client;
Fixed

2024-09-27 12:30 UTC, fractal3000 commented on jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/impl/ElasticsearchIndexManager.java
> +                                     ElasticsearchIndexStateResolver metadataResolver,
Fixed

2024-09-27 12:30 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexStateResolver.java
> + * The abstract class for all implementations that receive the index state from the search engine service.
Fixed

2024-09-27 12:30 UTC, fractal3000 commented on jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/impl/ElasticsearchIndexMappingComparator.java
>      protected JsonpSerializable extractTypeMapping(IndexState currentIndexState) {
Fixed

2024-09-27 12:30 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/IndexSettingsComparator.java
> + * Compares both the settings from the application's index configuration
Fixed

2024-09-27 12:30 UTC, fractal3000 commented on jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/impl/ElasticsearchIndexConfigurationComparator.java
Fixed. And fixed in all classes

2024-09-27 12:31 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/BaseJsonpSerializer.java
> + * The abstract class is respond of the transforming search clients' specific JSonp format to Jackson's ObjectNode.
Fixed

2024-09-27 12:31 UTC, fractal3000 commented on jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/impl/ElasticsearchPutMappingBuilder.java
> +public class ElasticsearchPutMappingBuilder implements PutMappingBuilder<PutMappingRequest, JsonpMapper> {
Fixed. The variables names was fixed too.

2024-09-27 12:31 UTC, fractal3000 commented on jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/impl/ElasticsearchPutMappingBuilder.java
> +    protected final ObjectMapper objectMapper = new ObjectMapper();
Fixed

2024-09-27 12:31 UTC, fractal3000 commented on jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/impl/ElasticsearchPutMappingBuilder.java
> +    public PutMappingRequest buildRequest(IndexMappingConfiguration mappingConfiguration, String indexName, JsonpMapper jsonpMapper) {
Fixed

2024-09-27 12:31 UTC, fractal3000 commented on jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/impl/ElastisearchIndexSettingsComparator.java
> +    protected final ElasticsearchIndexSettingsProvider settingsProvider;
Fixed

2024-09-27 12:31 UTC, fractal3000 commented on jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/impl/ElastisearchIndexSettingsComparator.java
> +    protected Optional<IndexSettings> extractAppliedIndexSettings(IndexState currentIndexState, String indexName) {
Fixed

2024-09-27 12:31 UTC, fractal3000 commented on jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/impl/ElastisearchIndexSettingsComparator.java
> +            throw new IllegalArgumentException(
Fixed

2024-09-27 12:31 UTC, fractal3000 commented on jmix-search/search-opensearch/src/main/java/io/jmix/searchopensearch/index/impl/OpenSearchJsonpSerializer.java
> +    protected final OpenSearchClient searchClient;
Fixed

2024-09-27 12:31 UTC, fractal3000 commented on jmix-search/search-opensearch/src/main/java/io/jmix/searchopensearch/index/impl/OpenSearchPutMappingRequestBuilder.java
> +    public static final TypeReference<Map<String, Object>> TYPE_REF = new TypeReference<>() {
Fixed

2024-09-27 12:31 UTC, fractal3000 commented on jmix-search/search-opensearch/src/main/java/io/jmix/searchopensearch/index/impl/OpenSearchPutMappingRequestBuilder.java
> +            throw new RuntimeException(MAPPING_CONFIGURATION_PARSING_EXCEPTION_TEXT, e);
Fixed

2024-09-27 12:31 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/IndexManager.java
> +     * @param mapping   - mapping for saving to configuration of the specified index
Fixed

2024-09-27 12:31 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/JsonNodesComparator.java
> + * Compares two JSon nodes that contains index settings or index mapping in correspondence to such comparison rules.
Fixed

2024-09-27 12:31 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/MappingComparingResult.java
> +    EQUAL,
Fixed

2024-09-27 12:31 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/JsonpSerializer.java
> +    ObjectNode toObjectNode(TJsonp object);
Fixed

2024-09-27 12:31 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/MappingFieldComparator.java
> + *
Fixed

2024-09-27 12:31 UTC, fractal3000 commented on jmix-search/search/src/main/java/io/jmix/search/index/impl/MappingFieldComparator.java
>      public static final String TYPE_KEY = "type";
Fixed

2024-09-27 15:22 UTC, Gavrilov-Ivan approved these changes

2024-09-27 15:22 UTC, Gavrilov-Ivan commented on jmix-search/search-elasticsearch-starter/src/main/java/io/jmix/autoconfigure/searchelasticsearch/SearchElasticsearchAutoConfiguration.java
> +                                                     ElasticsearchPutMappingRequestBuilder putMappingRequestService) {
Variable name

2024-09-27 22:15 UTC, fractal3000 commented on jmix-search/search-elasticsearch-starter/src/main/java/io/jmix/autoconfigure/searchelasticsearch/SearchElasticsearchAutoConfiguration.java
> +                                                     ElasticsearchPutMappingRequestBuilder putMappingRequestService) {
Fixed

2024-09-27 22:17 UTC, merged