Problem with setting default value to dinamic attribute which is of collection type #375
jmix-framework/jmix pull request #3627
Opened 2024-08-20 15:48 UTC by fractal3000

…ollection type

2024-08-20 20:02 UTC, glebfox requested changes

2024-08-20 20:02 UTC, glebfox commented on jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/view/categoryattr/CategoryAttributesDetailView.java
> +    protected void setEnabledAndClear(String componentId, boolean isEnabled, boolean clearValues) {
Rename method and input parameters

2024-08-20 20:02 UTC, glebfox commented on jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/view/categoryattr/CategoryAttributesDetailView.java
> +        ((HasEnabled)component).setEnabled(isEnabled);
1. Better to check if a component implements an interface before cast (for both interfaces).
2. Format code

2024-08-20 20:09 UTC, glebfox commented
@fractal3000 this solution prevents from creating **new** incorrect configurations in simple way, but it doesn't fixes existing configurations. 

In fact, we can define the default **collection** value using the same UI component as for editing such values.

2024-08-21 07:03 UTC, Gavrilov-Ivan requested changes

2024-08-30 06:53 UTC, closed without merging