Use browser timezone if user timezone is not set jmix-framework/jmix#3551
jmix-framework/jmix pull request #3750
Opened 2024-10-03 13:01 UTC by KremnevDmitry

See: #3551

2024-10-08 08:02 UTC, glebfox requested changes

2024-10-08 08:02 UTC, glebfox commented on jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/security/DeviceTimeZoneProviderImpl.java
> +@Component("flowui_DeviceTimeZoneProviderImpl")
As far as I see, beans inside this module has the `sec_` prefix.

2024-10-08 08:02 UTC, glebfox commented on jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/security/DeviceTimeZoneProviderImpl.java
> +    protected ExtendedClientDetailsProvider clientDetailsProvider;
Constructor injection?

2024-10-09 05:54 UTC, glebfox approved these changes

2024-10-09 07:57 UTC, knstvk approved these changes

2024-10-09 08:41 UTC, merged