Support for Accessing and Verifying Notifications and Dialogs for UI Testing
jmix-framework/jmix pull request #3762
Opened 2024-10-08 11:02 UTC by KremnevDmitry

See:
* #3409
* #3408

2024-10-08 13:05 UTC, Flaurite requested changes

2024-10-08 13:06 UTC, Flaurite commented on jmix-flowui/flowui-test-assist/src/main/java/io/jmix/flowui/testassist/JmixUiTestExtension.java
> +    protected void clearOpenedNotifications(ExtensionContext context) {
Add tests for dialogs and notifications to `flowui` module.

2024-10-08 13:53 UTC, KremnevDmitry commented on jmix-flowui/flowui-test-assist/src/main/java/io/jmix/flowui/testassist/notification/NotificationInfo.java
> +    protected boolean closeable;
Actually, not anymore :)

2024-10-09 14:16 UTC, Flaurite commented on jmix-flowui/flowui-test-assist/src/main/java/io/jmix/flowui/testassist/FlowuiTestAssistConfiguration.java
>  @Import({VaadinScopesConfig.class})
Add `ComponentScan` annotation. And change all bean prefixes to `flowui` excluding existing beans.

2024-10-09 14:19 UTC, Flaurite approved these changes

2024-10-09 14:25 UTC, KremnevDmitry commented
Will be merged after RC-1 release

2024-10-14 09:09 UTC, merged