Added CurrentLocaleQueryParamValueProvider #3958
jmix-framework/jmix pull request #3962
Opened 2024-12-02 14:48 UTC by dgodlevskiy

See https://github.com/jmix-framework/jmix/issues/3958

2024-12-06 07:14 UTC, glebfox requested changes

2024-12-06 07:14 UTC, glebfox commented on jmix-security/security-data/src/main/java/io/jmix/securitydata/impl/CurrentLocaleQueryParamValueProvider.java
> +@Order(JmixOrder.HIGHEST_PRECEDENCE + 100)
Let's make it `LOWEST_PRECEDENCE - 300`

2024-12-06 07:50 UTC, dgodlevskiy commented on jmix-security/security-data/src/main/java/io/jmix/securitydata/impl/CurrentLocaleQueryParamValueProvider.java
> +@Order(JmixOrder.HIGHEST_PRECEDENCE + 100)
done

2024-12-12 07:20 UTC, glebfox requested changes

2024-12-12 14:58 UTC, dgodlevskiy commented on jmix-security/security-data/src/main/java/io/jmix/securitydata/impl/CurrentLocaleQueryParamValueProvider.java
> +    private CurrentAuthentication currentAuthentication;
done

2024-12-12 14:58 UTC, dgodlevskiy commented on jmix-security/security-data/src/main/java/io/jmix/securitydata/impl/CurrentLocaleQueryParamValueProvider.java
> +    private CurrentAuthentication currentAuthentication;
done

2024-12-13 07:52 UTC, glebfox approved these changes

2024-12-13 07:52 UTC, merged