Improve performance of EntityStates.isLoaded operation
jmix-framework/jmix pull request #4002
Opened 2024-12-15 14:10 UTC by knstvk

2024-12-18 12:32 UTC, dtaimanov approved these changes

2024-12-18 14:18 UTC, dtaimanov commented
It is a problem with back reference and replacing existing references in entities after value holder loads entity.
see `io.jmix.eclipselink.impl.lazyloading.AbstractSingleValueHolder#afterLoadValue` and `io.jmix.eclipselink.impl.lazyloading.CollectionValuePropertyHolder#afterLoadValue`

patch to reproduce the issue: 
[LoadedPropertiesInfo_should_be_updated_when_ValueHolder_replaces_back_reference_and_existi.patch](https://github.com/user-attachments/files/18183789/LoadedPropertiesInfo_should_be_updated_when_ValueHolder_replaces_back_reference_and_existi.patch)

<img width="775" alt="Снимок экрана 2024-12-18 в 18 13 53" src="https://github.com/user-attachments/assets/44f33b5a-fa9b-4fde-9fda-90d9f19a99e9" />

It looks like `io.jmix.eclipselink.impl.lazyloading.AbstractValueHolder#replaceToExistingReferences` should invoke `io.jmix.eclipselink.impl.lazyloading.AbstractValueHolder#registerLoadedProperty` too at approptiate places

2024-12-18 14:35 UTC, dtaimanov requested changes
see https://github.com/jmix-framework/jmix/pull/4002#issuecomment-2551440172

2024-12-20 14:34 UTC, knstvk commented
> It looks like `io.jmix.eclipselink.impl.lazyloading.AbstractValueHolder#replaceToExistingReferences` should invoke `io.jmix.eclipselink.impl.lazyloading.AbstractValueHolder#registerLoadedProperty` too at approptiate places

Done

2024-12-22 19:18 UTC, dtaimanov approved these changes

2024-12-26 10:49 UTC, merged