Arbitrary fetch plans in generic REST endpoints
jmix-framework/jmix pull request #4042
Opened 2024-12-29 19:03 UTC by knstvk

2025-01-20 10:18 UTC, Gavrilov-Ivan requested changes

2025-01-20 10:18 UTC, Gavrilov-Ivan commented on jmix-rest/rest/src/main/java/io/jmix/rest/impl/service/QueriesControllerManager.java
> +                queryInfo.getFetchPlanName() != null ? queryInfo.getFetchPlanName() : queryInfo.getViewName());
Maybe we should remove (or deprecate at least) `viewName` field from `QueryInfo`?

2025-01-22 14:26 UTC, knstvk commented on jmix-rest/rest/src/main/java/io/jmix/rest/impl/controller/CapabilitiesController.java
> +@RequestMapping(path = "/rest/metadata/capabilities", produces = MediaType.APPLICATION_JSON_VALUE)
Done

2025-01-22 14:26 UTC, knstvk commented on jmix-rest/rest/src/main/java/io/jmix/rest/impl/service/QueriesControllerManager.java
> +                queryInfo.getFetchPlanName() != null ? queryInfo.getFetchPlanName() : queryInfo.getViewName());
Done

2025-01-22 14:30 UTC, Gavrilov-Ivan approved these changes

2025-01-23 06:45 UTC, merged